# -*- coding: utf-8 -*-
"""classifieur Bayésien Naïf .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0Dc_uIKLrbjS4nCGIpmXOTcavgId-my
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, roc_curve, auc

# Monter Google Drive
drive.mount('/content/drive')

# Chemins des fichiers train et test
train_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE train_file.csv"
test_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE test_file.csv"

# Charger les fichiers CSV
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

# Supprimer la colonne 'nombre of species'
df_train = df_train.drop(columns=['nombre of species'], errors='ignore')
df_test = df_test.drop(columns=['nombre of species'], errors='ignore')

# Séparer les features et les labels
X_train = df_train.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_train = df_train['label']
X_test = df_test.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_test = df_test['label']

# Normaliser les données
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Définir les hyperparamètres à optimiser
param_grid = {'var_smoothing': np.logspace(-9, 0, 10)}

# GridSearchCV pour trouver le meilleur hyperparamètre
model = GaussianNB()
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

# Meilleur modèle après optimisation
best_model = grid_search.best_estimator_

# Prédictions
y_pred = best_model.predict(X_test_scaled)
y_proba = best_model.predict_proba(X_test_scaled)[:, 1]

# Calcul de l'AUC et courbe ROC
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

# Tracer la courbe ROC
plt.figure()
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Courbe ROC - Naive Bayes')
plt.legend(loc='lower right')
roc_curve_path = "/content/drive/MyDrive/stage PFE naive_bayes_roc_curve.png"
plt.savefig(roc_curve_path)
plt.show()
print(f"Courbe ROC sauvegardée dans {roc_curve_path}")

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
specificity = conf_matrix[0, 0] / (conf_matrix[0, 0] + conf_matrix[0, 1])

# Afficher les résultats
print(f"Best var_smoothing: {grid_search.best_params_['var_smoothing']}")
print(f"Accuracy: {accuracy:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Specificity: {specificity:.4f}")
print(f"MCC: {mcc:.4f}")
print(f"AUC: {roc_auc:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

# Sauvegarder les résultats
output_path = "/content/drive/MyDrive/stage PFE naive_bayes_results.txt"
with open(output_path, "w") as file:
    file.write(f"Best var_smoothing: {grid_search.best_params_['var_smoothing']}\n")
    file.write(f"Accuracy: {accuracy:.4f}\n")
    file.write(f"Recall: {recall:.4f}\n")
    file.write(f"F1-score: {f1:.4f}\n")
    file.write(f"Specificity: {specificity:.4f}\n")
    file.write(f"MCC: {mcc:.4f}\n")
    file.write(f"AUC: {roc_auc:.4f}\n")
    file.write("Confusion Matrix:\n")
    file.write(np.array2string(conf_matrix))

print(f"Résultats sauvegardés dans {output_path}")

import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, matthews_corrcoef
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline

# Monter Google Drive
drive.mount('/content/drive')

# Chemins des fichiers train et test
train_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE train_file.csv"
test_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE test_file.csv"

# Charger les fichiers CSV avec gestion des données manquantes
df_train = pd.read_csv(train_path).dropna()
df_test = pd.read_csv(test_path).dropna()

# Supprimer la colonne 'nombre of species'
df_train = df_train.drop(columns=['nombre of species'], errors='ignore')
df_test = df_test.drop(columns=['nombre of species'], errors='ignore')

# Séparer les features et les labels
X_train = df_train.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_train = df_train['label']
X_test = df_test.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_test = df_test['label']

# Création d'un pipeline avec prétraitement et modèle
pipeline = Pipeline([
    ('scaler', RobustScaler()),  # Plus robuste aux outliers
    ('model', GaussianNB())
])

# Définir les hyperparamètres à optimiser avec plage élargie
param_grid = {
    'model__var_smoothing': np.logspace(-12, 0, 50)  # Recherche plus fine
}

# Configuration avancée de validation croisée
cv_strategy = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# GridSearchCV avec pipeline intégré
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=cv_strategy,
    scoring='accuracy',
    n_jobs=-1,  #Utilisation de tous les cœurs CPU
    verbose=1
)

# Entraînement avec gestion de l'équilibre des classes
grid_search.fit(X_train, y_train)

# Meilleur modèle après optimisation
best_model = grid_search.best_estimator_

# Prédictions et évaluation
y_pred = best_model.predict(X_test)

# Calcul des métriques amélioré
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average='weighted')  # Gestion multiclasse
f1 = f1_score(y_test, y_pred, average='weighted')
mcc = matthews_corrcoef(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Calcul spécificité pour classification binaire
if conf_matrix.shape == (2, 2):
    specificity = conf_matrix[0, 0] / (conf_matrix[0, 0] + conf_matrix[0, 1])
else:
    specificity = None

# Rapport détaillé
print("=== Rapport d'optimisation ===")
print(f"Meilleur paramètre: {grid_search.best_params_}")
print(f"Accuracy: {accuracy:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
if specificity:
    print(f"Specificity: {specificity:.4f}")
print(f"MCC: {mcc:.4f}")
print("Matrice de confusion:")
print(conf_matrix)

# Sauvegarde des résultats avec plus d'informations
output_path = "/content/drive/MyDrive/stage PFE naive_bayes_results_v2.txt"
with open(output_path, "w") as file:
    file.write(f"Meilleurs paramètres: {grid_search.best_params_}\n")
    file.write(f"Accuracy: {accuracy:.4f}\n")
    file.write(f"Recall: {recall:.4f}\n")
    file.write(f"F1-score: {f1:.4f}\n")
    if specificity:
        file.write(f"Specificity: {specificity:.4f}\n")
    file.write(f"MCC: {mcc:.4f}\n")
    file.write("Matrice de confusion:\n")
    file.write(np.array2string(conf_matrix))

print(f"\nRésultats sauvegardés dans {output_path}")