# -*- coding: utf-8 -*-
"""code step2 correct low.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cExt-sNftO7TaIqZsn08Q9CJEqTWS953
"""

from google.colab import drive
import pandas as pd
import re

drive.mount('/content/drive')

def process_mirna_data(input_file_path, output_file_path):
    """
    Extrait les données de miRNA d'un fichier texte et les enregistre dans un fichier CSV.

    Args:
        input_file_path (str): Chemin vers le fichier texte d'entrée.
        output_file_path (str): Chemin vers le fichier CSV de sortie.
    """

    data = []
    with open(input_file_path, 'r') as f:
        content = f.read()

        # Extraction des blocs de données pour chaque paire de miRNA
        blocks = re.findall(r'Paire: (.+?)\nEspèce (.+?)\nEspèce (.+?)\nScore: (.+?)\nIdentité: (.+?)\nAlignement (.+?):\n(.+?)\nAlignement (.+?):\n(.+?)\n', content, re.DOTALL) #Fixed indentation: This line was indented one space too many. It should align with the 'content = f.read()' line.

        for block in blocks:
            pair_name, species1, species2, score, identity, align1_label, seq1, align2_label, seq2 = block

            # Extraction des noms de miRNA (simplifié)
            mirna1_code = pair_name.split(' vs ')[0].strip()
            mirna2_code = pair_name.split(' vs ')[1].strip()

            # Ajout des données pour le premier miRNA (s'il n'existe pas déjà)
            if not any(d['code de miRNA'] == mirna1_code for d in data):
                data.append({
                    'code de miRNA': mirna1_code,
                    'nombre of species': 1,
                    'séquence de miRNA': seq1.strip(),
                    'espèce': species1.strip()
                })

            # Ajout des données pour le deuxième miRNA (s'il n'existe pas déjà)
            if not any(d['code de miRNA'] == mirna2_code for d in data):
                data.append({
                    'code de miRNA': mirna2_code,
                    'nombre of species': 1,
                    'séquence de miRNA': seq2.strip(),
                    'espèce': species2.strip()
                })

    # Création du DataFrame et enregistrement dans un fichier CSV
    df = pd.DataFrame(data)
    df.to_csv(output_file_path, index=False)
    # Exemple d'utilisation (remplacez avec vos chemins de fichiers)
input_file_path = '/content/drive/MyDrive/stage PFE/low_identity2.txt'  # Chemin vers votre fichier d'entrée
output_file_path = '/content/drive/MyDrive/stage PFE /low_identity_correct1.csv'  # Chemin pour enregistrer le fichier CSV



process_mirna_data(input_file_path, output_file_path)
print(f"Fichier CSV enregistré avec succès à : {output_file_path}")