# -*- coding: utf-8 -*-
"""combined_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Shgedp6GZgJAyoe-fIKFu4UZTaZAjWFw
"""

import pandas as pd
from google.colab import drive
import random
from sklearn.model_selection import train_test_split

# Monter Google Drive pour accéder aux fichiers
drive.mount('/content/drive')

# Chemins des fichiers CSV sur Google Drive
file_path_1 = "/content/drive/MyDrive/stage PFE /high_identity0 - high_identity0.csv"  # Remplacez par le chemin réel
file_path_2 = "/content/drive/MyDrive/stage PFE /low_identity_correct - low_identity_correct.csv"  # Remplacez par le chemin réel

# Lecture des fichiers CSV
df1 = pd.read_csv(file_path_1)
df2 = pd.read_csv(file_path_2)

# Ajouter la colonne "label" (1 pour le premier fichier, 0 pour le deuxième fichier)
df1['label'] = 1
df2['label'] = 0

# Fusionner les deux DataFrames
df_combined = pd.concat([df1, df2], ignore_index=True)

# Mélanger aléatoirement les lignes
df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)

# Supprimer les colonnes vides (qui ne contiennent aucune valeur)
df_combined = df_combined.dropna(axis=1, how='all')

# Supprimer les colonnes spécifiques
columns_to_remove = ['x_20', 'y_20', 'z_20', 'x_21', 'y_21', 'z_21', 'x_22', 'y_22', 'z_22',
                     'x_23', 'y_23', 'z_23', 'x_24', 'y_24', 'z_24']
df_combined = df_combined.drop(columns=[col for col in columns_to_remove if col in df_combined.columns])

# Chemin du fichier de sortie
output_path = "/content/drive/MyDrive/stage PFE combined_file.csv"

# Sauvegarder le fichier fusionné
df_combined.to_csv(output_path, index=False)

print("Fusion des fichiers terminée avec succès !")
print(f"Fichier enregistré à : {output_path}")

print(df_combined.columns)

# Division des données en 85% train et 15% test
df_train, df_test = train_test_split(df_combined, test_size=0.15, random_state=42)

# Chemins des fichiers de sortie
train_path = "/content/drive/MyDrive/stage PFE train_file.csv"
test_path = "/content/drive/MyDrive/stage PFE test_file.csv"

# Sauvegarder les fichiers train et test
df_train.to_csv(train_path, index=False)
df_test.to_csv(test_path, index=False)

print("Données divisées en train (85%) et test (15%) !")
print(f"Fichier train enregistré à : {train_path}")
print(f"Fichier test enregistré à : {test_path}")

print(df_train.columns)