# -*- coding: utf-8 -*-
"""lolipop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ct5aA88ZxwRvTQay_2Ftto6VCdRlN8n5
"""

# Monter Google Drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# === 1. Charger le fichier Excel ===
excel_path = "/content/drive/MyDrive/scoring_miRNA_targets_sans mfe miRNA_avec mfe.xlsx"
df = pd.read_excel(excel_path)

print(f"📊 Total des interactions initiales : {len(df)}")

# === 2. Liste des interactions spécifiques identifiées ===
clivage_interactions = [
    {"MiRNA_ID": "sbi-miR1432", "Symbole_gene": "APP", "Position": 287},
    {"MiRNA_ID": "sbi-miR1432", "Symbole_gene": "CR1", "Position": 940},
    {"MiRNA_ID": "pde-miR390", "Symbole_gene": "CLU", "Position": 877},
    {"MiRNA_ID": "aau-miR396", "Symbole_gene": "PSEN2", "Position": 738},
    {"MiRNA_ID": "aly-miR156c-3p", "Symbole_gene": "PSEN2", "Position": 321},
    {"MiRNA_ID": "aly-miR156c-3p", "Symbole_gene": "CR1", "Position": 1888},
    {"MiRNA_ID": "gma-miR390b-5p", "Symbole_gene": "NEFL", "Position": None}  # Position à vérifier
]

inhibition_interactions = [
    {"MiRNA_ID": "cpa-miR164d", "Symbole_gene": "PICALM", "Position": 1009},
    {"MiRNA_ID": "osa-miR444f", "Symbole_gene": "PICALM", "Position": 666},
    {"MiRNA_ID": "cca-miR396b", "Symbole_gene": "ABCA7", "Position": 108},
    {"MiRNA_ID": "sbi-miR396e", "Symbole_gene": "PSEN2", "Position": 738},
    {"MiRNA_ID": "ata-miR6201-5p", "Symbole_gene": "APP", "Position": 114}
]

# === 3. Récupérer les données pour les interactions de clivage ===
print("\n🔍 RECHERCHE DES INTERACTIONS DE CLIVAGE :")
clivage_data = []

for interaction in clivage_interactions:
    miRNA = interaction["MiRNA_ID"]
    gene = interaction["Symbole_gene"]
    position = interaction["Position"]

    # Filtrer selon les critères
    if position:
        query = f"MiRNA_ID == '{miRNA}' and Symbole_gene == '{gene}' and Position == {position}"
    else:
        query = f"MiRNA_ID == '{miRNA}' and Symbole_gene == '{gene}'"

    matches = df.query(query)

    if len(matches) > 0:
        row = matches.iloc[0]
        clivage_data.append({
            "MiRNA_ID": miRNA,
            "Symbole_gene": gene,
            "Position": row["Position"],
            "Score_final": row["Score_final"],
            "mfe_kcal/mol": row["mfe_kcal/mol"],
            "MiRNA_mfe_kcal/mol": row["MiRNA_mfe_kcal/mol"],
            "Type_seed_canonique": row["Type_seed_canonique"],
            "central_10_11_WC": row["central_10_11_WC"],
            "Type_UTR": row["Type_UTR"],
            "Type": "Clivage"
        })
        print(f"   ✅ {miRNA} -> {gene} (pos {row['Position']}) - Score: {row['Score_final']:.2f}")
    else:
        print(f"   ❌ {miRNA} -> {gene} NON TROUVÉ")

# === 4. Récupérer les données pour les interactions d'inhibition ===
print("\n🔍 RECHERCHE DES INTERACTIONS D'INHIBITION :")
inhibition_data = []

for interaction in inhibition_interactions:
    miRNA = interaction["MiRNA_ID"]
    gene = interaction["Symbole_gene"]
    position = interaction["Position"]

    # Filtrer selon les critères
    if position:
        query = f"MiRNA_ID == '{miRNA}' and Symbole_gene == '{gene}' and Position == {position}"
    else:
        query = f"MiRNA_ID == '{miRNA}' and Symbole_gene == '{gene}'"

    matches = df.query(query)

    if len(matches) > 0:
        row = matches.iloc[0]
        inhibition_data.append({
            "MiRNA_ID": miRNA,
            "Symbole_gene": gene,
            "Position": row["Position"],
            "Score_final": row["Score_final"],
            "mfe_kcal/mol": row["mfe_kcal/mol"],
            "MiRNA_mfe_kcal/mol": row["MiRNA_mfe_kcal/mol"],
            "Type_seed_canonique": row["Type_seed_canonique"],
            "central_10_11_WC": row["central_10_11_WC"],
            "Type_UTR": row["Type_UTR"],
            "Type": "Inhibition"
        })
        print(f"   ✅ {miRNA} -> {gene} (pos {row['Position']}) - Score: {row['Score_final']:.2f}")
    else:
        print(f"   ❌ {miRNA} -> {gene} NON TROUVÉ")

# === 5. Créer le DataFrame final ===
all_interactions = clivage_data + inhibition_data
if len(all_interactions) == 0:
    print("❌ AUCUNE interaction trouvée. Vérifiez les noms des miRNAs et gènes.")
    exit()

df_final = pd.DataFrame(all_interactions)

print(f"\n🎯 TOTAL INTERACTIONS TROUVÉES : {len(df_final)}")
print(f"   - Clivage : {len(clivage_data)}")
print(f"   - Inhibition : {len(inhibition_data)}")

# === 6. Agrégation par gène ===
agg = (
    df_final.groupby("Symbole_gene")
    .agg(
        Score_final_agrege=("Score_final", "mean"),
        n=("MiRNA_ID", "count"),
        types=("Type", lambda x: "/".join(x.unique()))
    )
    .reset_index()
)

top_genes = agg.sort_values("Score_final_agrege", ascending=False)

print(f"\n📈 GÈNES AGRÉGÉS :")
print(top_genes[['Symbole_gene', 'Score_final_agrege', 'n', 'types']].to_string(index=False))

# === 7. Tracé du graphique "lollipop" ===
plt.figure(figsize=(12, 8))

# Lollipop plot
plt.hlines(
    y=top_genes["Symbole_gene"],
    xmin=0,
    xmax=top_genes["Score_final_agrege"],
    color="grey",
    alpha=0.6,
    linewidth=3
)

# Points colorés par type d'interaction
colors = []
for gene in top_genes["Symbole_gene"]:
    gene_data = df_final[df_final["Symbole_gene"] == gene]
    if len(gene_data[gene_data["Type"] == "Clivage"]) > 0 and len(gene_data[gene_data["Type"] == "Inhibition"]) > 0:
        colors.append("purple")  # Mixte
    elif len(gene_data[gene_data["Type"] == "Clivage"]) > 0:
        colors.append("red")     # Clivage seulement
    else:
        colors.append("blue")    # Inhibition seulement

plt.scatter(
    top_genes["Score_final_agrege"],
    top_genes["Symbole_gene"],
    s=100,
    c=colors
)

# Annotations
for i, (x, y, n, gene, types) in enumerate(zip(
    top_genes["Score_final_agrege"],
    top_genes["Symbole_gene"],
    top_genes["n"],
    top_genes["Symbole_gene"],
    top_genes["types"]
)):
    plt.text(x + 0.1, y, f"n={n}", va='center', fontsize=10, fontweight='bold')

plt.title("Top gènes cibles Alzheimer - 10 interactions sélectionnées\n(5 Clivage + 5 Inhibition)",
          fontsize=14, fontweight='bold')
plt.xlabel("Score final agrégé", fontsize=12)
plt.ylabel("Gènes cibles", fontsize=12)

# Légende
from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='red', label='Clivage'),
    Patch(facecolor='blue', label='Inhibition'),
    Patch(facecolor='purple', label='Mixte')
]
plt.legend(handles=legend_elements, loc='lower right')

plt.grid(axis='x', alpha=0.3)
plt.tight_layout()

# === 8. Sauvegarde ===
output_path = "/content/drive/MyDrive/lollipop_output_alzheimer_final.png"
plt.savefig(output_path, dpi=300, bbox_inches='tight')
plt.show()

print(f"\n✅ Figure enregistrée : {output_path}")

# === 9. Tableau détaillé des interactions ===
print(f"\n📋 TABLEAU DÉTAILLÉ DES 10 INTERACTIONS :")
df_display = df_final[['MiRNA_ID', 'Symbole_gene', 'Position', 'Score_final', 'Type_seed_canonique', 'Type']].copy()
df_display = df_display.sort_values(['Type', 'Score_final'], ascending=[True, False])
print(df_display.to_string(index=False))

# === 10. Statistiques supplémentaires ===
print(f"\n📊 STATISTIQUES :")
print(f"Score_final moyen : {df_final['Score_final'].mean():.2f}")
print(f"Score_final médian : {df_final['Score_final'].median():.2f}")
print(f"MFE moyen : {df_final['mfe_kcal/mol'].mean():.2f}")
print(f"Stabilité miRNA moyenne : {df_final['MiRNA_mfe_kcal/mol'].mean():.2f}")

# Vérification des critères
print(f"\n✅ VÉRIFICATION DES CRITÈRES :")
print(f"Clivage avec central_10_11_WC=True : {df_final[df_final['Type']=='Clivage']['central_10_11_WC'].all()}")
print(f"Inhibition avec central_10_11_WC=False : {df_final[df_final['Type']=='Inhibition']['central_10_11_WC'].all()}")