# -*- coding: utf-8 -*-
"""ML stage PFE regression logistique .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFnTojKM0f2g_2eMsMtJ4HOys5fodPRv
"""

from google.colab import drive
# Monter Google Drive pour accéder aux fichiers
drive.mount('/content/drive')

"""**regression logistique**"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, matthews_corrcoef, roc_curve, auc
import numpy as np
from google.colab import drive

# Monter Google Drive
drive.mount('/content/drive')

# Chemins des fichiers CSV
train_file_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE train_file.csv"
test_file_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE test_file.csv"

# Charger les données
train_df = pd.read_csv(train_file_path)
test_df = pd.read_csv(test_file_path)

# Sélectionner les features et la variable cible
features_to_exclude = ['code de miRNA', 'nombre of species', 'séquence de miRNA', 'espèce', 'label']
X_train = train_df.drop(columns=features_to_exclude, errors='ignore')
y_train = train_df['label']
X_test = test_df.drop(columns=features_to_exclude, errors='ignore')
y_test = test_df['label']

# Création et entraînement du modèle
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Prédictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probabilité de la classe positive

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Calcul de la courbe ROC et de l'AUC
fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

# Affichage des résultats
def print_metrics():
    print("Évaluation du modèle de régression logistique :")
    print(f"Exactitude (Accuracy) : {accuracy:.4f}")
    print(f"Rappel (Recall) : {recall:.4f}")
    print(f"Score F1 : {f1:.4f}")
    print(f"MCC : {mcc:.4f}")
    print(f"AUC : {roc_auc:.4f}")
    print("Matrice de confusion :")
    print(conf_matrix)

print_metrics()

# Sauvegarde des résultats dans un fichier texte
results_path = "/content/drive/MyDrive/stage PFE logistic_regression_results.txt"
with open(results_path, "w") as f:
    f.write("Évaluation du modèle de régression logistique :\n")
    f.write(f"Exactitude (Accuracy) : {accuracy:.4f}\n")
    f.write(f"Rappel (Recall) : {recall:.4f}\n")
    f.write(f"Score F1 : {f1:.4f}\n")
    f.write(f"MCC : {mcc:.4f}\n")
    f.write(f"AUC : {roc_auc:.4f}\n")
    f.write("Matrice de confusion :\n")
    f.write(np.array2string(conf_matrix))

print(f"Résultats enregistrés dans {results_path}")

# Tracer et enregistrer la courbe ROC
plt.figure()
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Taux de Faux Positifs (FPR)')
plt.ylabel('Taux de Vrais Positifs (TPR)')
plt.title('Courbe ROC')
plt.legend(loc='lower right')
roc_curve_path = "/content/drive/MyDrive/stage PFE logistic_regression_roc_curve.png"
plt.savefig(roc_curve_path)
plt.show()

print(f"Courbe ROC enregistrée dans {roc_curve_path}")

# Optionnel: Affichage des probabilités pour quelques échantillons
print("\nExemple de probabilités prédites (5 premiers échantillons):")
for i in range(5):
    print(f"Échantillon {i+1}: Probabilité = {y_prob[i]:.4f} => Prédiction = {y_pred_threshold[i]} (Réel = {y_test.iloc[i]})")

"""**Regressio logistique + LASSO + Résultat de LASSO en csv**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, matthews_corrcoef, roc_curve, auc
from sklearn.preprocessing import StandardScaler

# Monter Google Drive
drive.mount('/content/drive')

# Chemins des fichiers CSV
train_file_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE train_file.csv"
test_file_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE test_file.csv"

# Charger les données
train_df = pd.read_csv(train_file_path)
test_df = pd.read_csv(test_file_path)

# Sélectionner les features et la variable cible
features_to_exclude = ['code de miRNA', 'nombre of species', 'séquence de miRNA', 'espèce', 'label']
X_train = train_df.drop(columns=features_to_exclude, errors='ignore')
y_train = train_df['label']
X_test = test_df.drop(columns=features_to_exclude, errors='ignore')
y_test = test_df['label']

# Normalisation des données
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Création et entraînement du modèle avec régularisation L1 (Lasso)
model = LogisticRegression(penalty='l1', solver='liblinear', max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)

# Extraction du paramètre lambda (λ = 1/C)
lambda_value = 1 / model.C
print(f"Valeur du paramètre de régularisation lambda: {lambda_value:.4f}")

# Prédictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]  # Probabilité de la classe positive

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Calcul de la courbe ROC et de l'AUC
fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

# Affichage des résultats
def print_metrics():
    print("Évaluation du modèle de régression logistique avec Lasso :")
    print(f"Paramètre de régularisation (lambda) : {lambda_value:.4f}")  # Nouvelle ligne
    print(f"Exactitude (Accuracy) : {accuracy:.4f}")
    print(f"Rappel (Recall) : {recall:.4f}")
    print(f"Score F1 : {f1:.4f}")
    print(f"MCC : {mcc:.4f}")
    print(f"AUC : {roc_auc:.4f}")
    print("Matrice de confusion :")
    print(conf_matrix)

print_metrics()

# Sauvegarde des résultats dans un fichier texte
results_path = "/content/drive/MyDrive/stage PFE logistic_regression_lasso_results.txt"
with open(results_path, "w") as f:
    f.write("Évaluation du modèle de régression logistique avec Lasso :\n")
    f.write(f"Paramètre de régularisation (lambda) : {lambda_value:.4f}\n")  # Nouvelle ligne
    f.write(f"Exactitude (Accuracy) : {accuracy:.4f}\n")
    f.write(f"Rappel (Recall) : {recall:.4f}\n")
    f.write(f"Score F1 : {f1:.4f}\n")
    f.write(f"MCC : {mcc:.4f}\n")
    f.write(f"AUC : {roc_auc:.4f}\n")
    f.write("Matrice de confusion :\n")
    f.write(np.array2string(conf_matrix))

print(f"Résultats enregistrés dans {results_path}")

# Tracer et enregistrer la courbe ROC
plt.figure()
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Taux de Faux Positifs (FPR)')
plt.ylabel('Taux de Vrais Positifs (TPR)')
plt.title('Courbe ROC')
plt.legend(loc='lower right')
roc_curve_path = "/content/drive/MyDrive/stage PFE logistic_regression_lasso_roc_curve.png"
plt.savefig(roc_curve_path)
plt.show()

print(f"Courbe ROC enregistrée dans {roc_curve_path}")

# Extraction des coefficients Lasso
coefficients = model.coef_[0]
feature_names = X_train.columns
lasso_coeffs = pd.DataFrame({"Feature": feature_names, "Coefficient": coefficients})

# Ajouter une colonne indiquant si le coefficient est supprimé ou retenu
lasso_coeffs['Retained'] = lasso_coeffs['Coefficient'].apply(lambda x: 'Retained' if x != 0 else 'Zeroed')

# Sauvegarde des coefficients dans un fichier CSV
output_coeffs_path = "/content/drive/MyDrive/stage PFE lasso_coefficients.csv"
lasso_coeffs.to_csv(output_coeffs_path, index=False)
print(f"Coefficients de Lasso sauvegardés dans : {output_coeffs_path}")

"""**regression logistique + LASSO + GridSearchCV**

"""

import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, matthews_corrcoef, roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt

# Monter Google Drive
drive.mount('/content/drive')

# Chemins des fichiers train et test
train_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE train_file.csv"
test_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE test_file.csv"

# Charger les fichiers CSV
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

# Supprimer la colonne 'nombre of species'
df_train = df_train.drop(columns=['nombre of species'], errors='ignore')
df_test = df_test.drop(columns=['nombre of species'], errors='ignore')

X_train = df_train.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_train = df_train['label']
X_test = df_test.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_test = df_test['label']

# Normaliser les données
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Définir les valeurs de C à tester (C = 1/𝜆)
C_values = [0.01, 0.1, 1, 100, 1000, 3000]

# GridSearchCV pour trouver le meilleur C
lasso = LogisticRegression(penalty='l1', solver='liblinear', random_state=42)
grid = GridSearchCV(lasso, param_grid={'C': C_values}, cv=5, scoring='accuracy')
grid.fit(X_train_scaled, y_train)

# Meilleur C trouvé
best_C = grid.best_params_['C']
best_lambda = 1 / best_C  # Conversion en lambda
print(f"Meilleur C trouvé : {best_C}")
print(f"Valeur correspondante de λ (lambda) : {best_lambda:.4f}")

# Entraîner le modèle avec le meilleur C
model = LogisticRegression(penalty='l1', solver='liblinear', C=best_C, random_state=42)
model.fit(X_train_scaled, y_train)

# Prédictions avec seuil de 0.5
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]  # Probabilités de la classe positive

# Calcul du catof (taux de classification) avec seuil à 0.5
threshold = 0.5
y_pred_threshold = (y_prob >= threshold).astype(int)
catof = accuracy_score(y_test, y_pred_threshold)

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
specificity = conf_matrix[0, 0] / (conf_matrix[0, 0] + conf_matrix[0, 1])

# Afficher les résultats
print("\n" + "="*50)
print("Résultats avec seuil par défaut (0.5):")
print(f"Accuracy (CatOF): {catof:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Specificity: {specificity:.4f}")
print(f"MCC: {mcc:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

# Sauvegarder les résultats
results_path = "/content/drive/MyDrive/stage PFE lasso_results.txt"
with open(results_path, "w") as file:
    file.write(f"Meilleur C trouvé : {best_C}\n")
    file.write(f"Valeur de lambda (𝜆) : {best_lambda:.4f}\n")
    file.write("\nRésultats avec seuil à 0.5:\n")
    file.write(f"Accuracy (CatOF): {catof:.4f}\n")
    file.write(f"Recall: {recall:.4f}\n")
    file.write(f"F1-score: {f1:.4f}\n")
    file.write(f"Specificity: {specificity:.4f}\n")
    file.write(f"MCC: {mcc:.4f}\n")
    file.write("Confusion Matrix:\n")
    file.write(np.array2string(conf_matrix))

print(f"Résultats enregistrés dans : {results_path}")

# Obtenir les coefficients de Lasso
coefficients = model.coef_[0]
features = X_train.columns
lasso_results = pd.DataFrame({'Feature': features, 'Coefficient': coefficients})

# Ajouter une colonne indiquant si le coefficient est supprimé ou retenu
lasso_results['Retained'] = lasso_results['Coefficient'].apply(lambda x: 'Retained' if x != 0 else 'Zeroed')

# Sauvegarder tous les coefficients dans un seul fichier CSV
coefficients_path = "/content/drive/MyDrive/stage PFE lasso_coefficients.csv"
lasso_results.to_csv(coefficients_path, index=False)
print(f"Coefficients sauvegardés dans : {coefficients_path}")

# Calculer la courbe ROC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = roc_auc_score(y_test, y_prob)

# Afficher la courbe ROC
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='blue', lw=2, label=f'Courbe ROC (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlabel('Taux de faux positifs (FPR)')
plt.ylabel('Taux de vrais positifs (TPR)')
plt.title('Courbe ROC')
plt.legend(loc='lower right')
plt.grid(True)

# Sauvegarder la courbe ROC dans le Drive
roc_curve_path = "/content/drive/MyDrive/stage PFE Lasso_courbe_ROC.png"
plt.savefig(roc_curve_path)
print(f"Courbe ROC sauvegardée dans : {roc_curve_path}")

# Affichage dans le notebook
plt.show()

# Afficher AUC
print(f"AUC (Area Under the Curve): {roc_auc:.4f}")

# Optionnel: Affichage des probabilités pour quelques échantillons
print("\nExemple de probabilités prédites (5 premiers échantillons):")
for i in range(5):
    print(f"Échantillon {i+1}: Probabilité = {y_prob[i]:.4f} => Prédiction = {y_pred_threshold[i]} (Réel = {y_test.iloc[i]})")

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import joblib
import matplotlib.pyplot as plt

# === Chemins ===
new_data_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE selected_non_conserved_miRNAs3.csv"
output_predictions_path = "/content/drive/MyDrive/stage PFE lasso_predictions_on_new_data.csv"

# === Charger le nouveau jeu de données ===
new_df = pd.read_csv(new_data_path)

# Sauvegarder les identifiants (si dispo)
if 'code de miRNA' in new_df.columns:
    mirna_ids = new_df['code de miRNA']
else:
    mirna_ids = pd.Series(np.arange(len(new_df)), name='code de miRNA')

# Supprimer les colonnes non utilisées
X_new = new_df.drop(columns=['code de miRNA', 'séquence de miRNA', 'espèce', 'nombre of species'], errors='ignore')

# === Gérer les NaN : remplacer par la moyenne ===
imputer = SimpleImputer(strategy='mean')
X_new_imputed = imputer.fit_transform(X_new)

# === Normaliser avec le scaler déjà entraîné ===
X_new_scaled = scaler.transform(X_new_imputed)

# === Prédire avec le modèle ===
y_new_prob = model.predict_proba(X_new_scaled)[:, 1]
y_new_pred = (y_new_prob >= 0.5).astype(int)

# === Résultats dans un DataFrame ===
results_df = pd.DataFrame({
    'code de miRNA': mirna_ids,
    'Probabilité classe 1': y_new_prob,
    'Prédiction': y_new_pred
})

# === Sauvegarder les résultats ===
results_df.to_csv(output_predictions_path, index=False)
print(f"\n Prédictions sauvegardées dans : {output_predictions_path}\n")

# === Affichage des résultats dans Colab ===

# Afficher les 5 premières prédictions
print(" Aperçu des 5 premières prédictions :")
display(results_df.head())

# Statistiques de répartition
print("\n Répartition des classes prédites :")
print(results_df['Prédiction'].value_counts())

# Afficher les 10 miRNAs avec la plus haute probabilité d'être positifs
print("\n Top 10 des miRNAs les plus probables (classe 1) :")
display(results_df.sort_values(by='Probabilité classe 1', ascending=False).head(10))

# Histogramme des probabilités
plt.figure(figsize=(8, 5))
plt.hist(y_new_prob, bins=30, color='skyblue', edgecolor='black')
plt.title("Distribution des probabilités prédites (classe 1)")
plt.xlabel("Probabilité")
plt.ylabel("Nombre de miRNAs")
plt.grid(True)
plt.show()