# -*- coding: utf-8 -*-
"""PFE KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cijuShCG7TpHTFXPRuwZSP_s3mf8ICKo
"""

import pandas as pd
import numpy as np
from google.colab import drive
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, roc_curve, auc

# Monter Google Drive
drive.mount('/content/drive')

# Chemins des fichiers train et test
train_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE train_file.csv"
test_path = "/content/drive/MyDrive/stage PFE ML classifieur /stage PFE test_file.csv"

# Charger les fichiers CSV
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

# Supprimer la colonne 'nombre of species'
df_train = df_train.drop(columns=['nombre of species'], errors='ignore')
df_test = df_test.drop(columns=['nombre of species'], errors='ignore')

# Séparer les features et les labels
X_train = df_train.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_train = df_train['label']
X_test = df_test.drop(columns=['label', 'code de miRNA', 'séquence de miRNA', 'espèce'])
y_test = df_test['label']

# Normaliser les données
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Définir les hyperparamètres à tester
param_grid = {
    'n_neighbors': [12],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

# GridSearchCV pour trouver les meilleurs hyperparamètres
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train_scaled, y_train)

# Meilleurs hyperparamètres trouvés
best_params = grid.best_params_
print(f"Meilleurs hyperparamètres trouvés : {best_params}")

# Entraîner le modèle avec les meilleurs hyperparamètres
model = KNeighborsClassifier(**best_params)
model.fit(X_train_scaled, y_train)

# Prédictions
y_pred = model.predict(X_test_scaled)
y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]  # Probabilité de la classe positive

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
specificity = conf_matrix[0, 0] / (conf_matrix[0, 0] + conf_matrix[0, 1])

# Calcul de l'AUC et tracé de la courbe ROC
fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (area = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Courbe ROC')
plt.legend(loc='lower right')
roc_curve_path = "/content/drive/MyDrive/stage PFE knn_roc_curve.png"
plt.savefig(roc_curve_path)
print(f"Courbe ROC sauvegardée dans {roc_curve_path}")

# Afficher les résultats
print(f"Accuracy: {accuracy:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Specificity: {specificity:.4f}")
print(f"MCC: {mcc:.4f}")
print(f"AUC: {roc_auc:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

# Sauvegarder les résultats
output_path = "/content/drive/MyDrive/stage PFE knn_results.txt"
with open(output_path, "w") as file:
    file.write(f"Meilleurs hyperparamètres trouvés : {best_params}\n")
    file.write(f"Accuracy: {accuracy:.4f}\n")
    file.write(f"Recall: {recall:.4f}\n")
    file.write(f"F1-score: {f1:.4f}\n")
    file.write(f"Specificity: {specificity:.4f}\n")
    file.write(f"MCC: {mcc:.4f}\n")
    file.write(f"AUC: {roc_auc:.4f}\n")
    file.write("Confusion Matrix:\n")
    file.write(np.array2string(conf_matrix))

print(f"Résultats sauvegardés dans {output_path}")

